spring:
  datasource:
    url: jdbc:mysql://localhost:3306/programmerdb
    username: root
    password: _Imtheking007!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Programmer-Api